networks:
  izpbx:
    driver: bridge

services:
  db:
    image: docker.io/mariadb:10.11.11
    container_name: izpbx-db
    restart: unless-stopped
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - izpbx

  izpbx:
    image: docker.io/izdock/izpbx-asterisk:20.16.20
    container_name: izpbx
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - HTTPD_ENABLED=true
      - AST_MYSQL_SERVER=db
    volumes:
      - ./data/izpbx:/data
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor=unconfined
    privileged: true
    ulimits:
      nofile:
        soft: 8192
        hard: 32768
    ports:
      - ${APP_PORT_HTTP}:${APP_PORT_HTTP}
      - ${APP_PORT_HTTPS}:${APP_PORT_HTTPS}
      - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}/udp
      - ${APP_PORT_SIP}:${APP_PORT_SIP}/udp
      - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
      - ${APP_PORT_UCP_HTTP}:${APP_PORT_UCP_HTTP}
      - ${APP_PORT_UCP_HTTPS}:${APP_PORT_UCP_HTTPS}
      - ${APP_PORT_AMI}:${APP_PORT_AMI}
    networks:
      - izpbx
